---
title: "Final Project"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GDAT 515: Final Project
**Objective** develop a dashboard or application that provides a narrative analysis using RStudio: 
FlexDashnoard or R Shiny.

#### Step 1: Choose a Project Domain & Pose a Question
Choose a problem domain that inspires you or is from a field you aspire to work in. Using data related to your capstone projects is also fair game.    

If you're interested in any of the following, see me.   
- twitter data
- spotify Data
- food related data

If you need ideas, see me.

#### Step 2: Project Proposal   
Develop a project proposal with the following sections. 

**Statement of Work** - "A concise summary detailing the scope and objectives."   
**Problem Statement** - "What is the problem to be solved?", "How can it be use?" "What are some of the benefits?"

*Environment:*     
*Data Sources:*      
*Primary Package Dependencies:*  

This can be saved as the README document you create when you initialize your final project repo on github.

#### Requirements
- The db/app must be built using FlexDashnoard or R Shiny
- It should feature both ggplot2 and plotly graphs 
- There should be at least one interactive component (we will go over how to do this in class)

#### Presentation
On the day reserved for the final, you will each have 20 minutes to showcase your work. 

#### Remember!
 1. You're all Github users now! Take advantage of the functionality.   
 2. This is a data visualization course. All figures should have appropriate labels and titles and clearly illustrate the point you're trying to make. 